# Generated by Django 6.0.2 on 2026-03-01 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IndexPage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='Subscribe',
            field=models.EmailField(blank=True, max_length=250, null=True),
        ),
    ]
