# Generated by Django 6.0.2 on 2026-03-01 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IndexPage', '0002_alter_subscriber_subscribe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='Subscribe',
            new_name='email',
        ),
    ]
