# Generated by Django 6.0.2 on 2026-02-28 07:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0003_author_image_author_name_book_book_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='format',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='page',
            field=models.IntegerField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='publication_data',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
