# Generated by Django 6.0.2 on 2026-03-05 08:55

import Auth.models
import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=80, scale=None, size=[300, 200], upload_to=Auth.models.admin_profile),
        ),
    ]
