# Generated by Django 6.0.2 on 2026-03-05 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0004_user_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='full_name',
            new_name='name',
        ),
    ]
