# Generated by Django 6.0.2 on 2026-03-05 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0006_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
