# Generated by Django 6.0.2 on 2026-02-25 09:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0002_banner_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=250),
        ),
    ]
