# Generated by Django 6.0.2 on 2026-02-26 09:37

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0003_alter_banner_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='on_offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sale_offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('discount', models.IntegerField(default=0)),
            ],
        ),
    ]
